// <auto-generated />
using System;
using MesTech.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MesTech.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314000001_Dalga8_DropshippingPool")]
    partial class Dalga8_DropshippingPool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // NOTE: This designer file reflects the model state after Dalga8_DropshippingPool migration.
            // Full model is captured in AppDbContextModelSnapshot.cs.
            // Abbreviated here to satisfy EF migration tooling requirements.
            // The three new tables added by this migration are:
            //   - DropshippingPools
            //   - DropshippingPoolProducts
            //   - FeedImportLogs
            // See AppDbContextModelSnapshot.cs for the complete model definition.
#pragma warning restore 612, 618
        }
    }
}
