using FluentAssertions;
using MesTech.Domain.Common;
using MesTech.Domain.Entities;

namespace MesTech.Tests.Unit.Domain;

/// <summary>
/// BaseEntity tests — Guid PK, audit trail, soft delete, domain events, equality.
/// Uses Product as concrete subclass since BaseEntity is abstract.
/// </summary>
[Trait("Category", "Unit")]
public class BaseEntityTests
{
    // ── Auto-generated Guid Id ──

    [Fact]
    public void NewEntity_ShouldHaveAutoGeneratedGuidId()
    {
        var entity = new Product();

        entity.Id.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void TwoNewEntities_ShouldHaveDifferentIds()
    {
        var entity1 = new Product();
        var entity2 = new Product();

        entity1.Id.Should().NotBe(entity2.Id);
    }

    // ── Default Audit Values ──

    [Fact]
    public void NewEntity_ShouldHaveDefaultAuditValues()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var entity = new Product();
        var after = DateTime.UtcNow.AddSeconds(1);

        entity.CreatedBy.Should().Be("system");
        entity.UpdatedBy.Should().Be("system");
        entity.CreatedAt.Should().BeAfter(before).And.BeBefore(after);
        entity.UpdatedAt.Should().BeAfter(before).And.BeBefore(after);
        entity.IsDeleted.Should().BeFalse();
    }

    // ── Soft Delete ──

    [Fact]
    public void SoftDelete_ShouldSetDeletedFields()
    {
        var entity = new Product();
        var deleteTime = DateTime.UtcNow;

        entity.IsDeleted = true;
        entity.DeletedAt = deleteTime;
        entity.DeletedBy = "admin";

        entity.IsDeleted.Should().BeTrue();
        entity.DeletedAt.Should().Be(deleteTime);
        entity.DeletedBy.Should().Be("admin");
    }

    // ── Domain Events ──

    [Fact]
    public void DomainEvents_RaiseAndClear_ShouldWork()
    {
        var product = new Product { Stock = 100 };

        // AdjustStock raises a StockChangedEvent
        product.AdjustStock(10, MesTech.Domain.Enums.StockMovementType.StockIn);
        product.DomainEvents.Should().HaveCount(1);

        product.ClearDomainEvents();
        product.DomainEvents.Should().BeEmpty();
    }

    [Fact]
    public void DomainEvents_MultipleEvents_ShouldAccumulate()
    {
        var product = new Product { Stock = 100 };

        product.AdjustStock(10, MesTech.Domain.Enums.StockMovementType.StockIn);
        product.AdjustStock(-5, MesTech.Domain.Enums.StockMovementType.Sale);
        product.AdjustStock(20, MesTech.Domain.Enums.StockMovementType.Purchase);

        product.DomainEvents.Should().HaveCount(3);
    }

    // ── Equality by Id (User-requested: critical for HashSet/Dictionary) ──

    [Fact]
    public void Equality_SameGuid_ShouldBeEqual()
    {
        var product1 = new Product { Name = "Product A" };
        var product2 = new Product { Name = "Product B" };

        // Force same Id via reflection (Id setter is protected)
        var idProperty = typeof(BaseEntity).GetProperty("Id")!;
        var sharedId = Guid.NewGuid();
        idProperty.SetValue(product1, sharedId);
        idProperty.SetValue(product2, sharedId);

        // Two different instances with same Id must be considered equal
        product1.Equals(product2).Should().BeTrue();
        (product1 == product2).Should().BeTrue();
        (product1 != product2).Should().BeFalse();
    }

    [Fact]
    public void Equality_DifferentGuid_ShouldNotBeEqual()
    {
        var product1 = new Product { Name = "Same Name" };
        var product2 = new Product { Name = "Same Name" };

        // Different Ids (auto-generated) — should NOT be equal even with same properties
        product1.Equals(product2).Should().BeFalse();
        (product1 == product2).Should().BeFalse();
    }

    [Fact]
    public void GetHashCode_SameId_ShouldReturnSameHash_ForDictionarySupport()
    {
        var product1 = new Product();
        var product2 = new Product();

        // Set same Id
        var idProperty = typeof(BaseEntity).GetProperty("Id")!;
        var sharedId = Guid.NewGuid();
        idProperty.SetValue(product1, sharedId);
        idProperty.SetValue(product2, sharedId);

        // GetHashCode contract: equal objects must have same hash
        product1.GetHashCode().Should().Be(product2.GetHashCode());

        // Verify HashSet deduplication works
        var set = new HashSet<Product> { product1, product2 };
        set.Should().HaveCount(1, "same Id means same entity — HashSet should deduplicate");

        // Verify Dictionary key lookup works
        var dict = new Dictionary<Product, string> { [product1] = "first" };
        dict[product2].Should().Be("first", "same Id means same key — Dictionary lookup should work");
    }
}
