using FluentAssertions;
using MesTech.Domain.Entities;
using MesTech.Domain.Enums;
using MesTech.Tests.Unit._Shared;

namespace MesTech.Tests.Unit.EdgeCases;

/// <summary>
/// BaseEntity edge case tests — equality, domain events, soft delete, audit fields.
/// Dalga 14 — DEV 5.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Phase", "Dalga14")]
public class BaseEntityEdgeCaseTests
{
    [Fact]
    public void Equals_SameEntity_ShouldReturnTrue()
    {
        var product = FakeData.CreateProduct();

        product.Equals(product).Should().BeTrue();
    }

    [Fact]
    public void Equals_DifferentEntitiesSameType_ShouldReturnFalse()
    {
        var a = FakeData.CreateProduct(sku: "A-001");
        var b = FakeData.CreateProduct(sku: "B-001");

        a.Equals(b).Should().BeFalse();
    }

    [Fact]
    public void Equals_Null_ShouldReturnFalse()
    {
        var product = FakeData.CreateProduct();

        product.Equals(null).Should().BeFalse();
    }

    [Fact]
    public void Equals_DifferentType_ShouldReturnFalse()
    {
        var product = FakeData.CreateProduct();
        var order = new Order();

        product.Equals(order).Should().BeFalse();
    }

    [Fact]
    public void OperatorEquals_BothNull_ShouldReturnTrue()
    {
        Product? a = null;
        Product? b = null;

        (a == b).Should().BeTrue();
    }

    [Fact]
    public void OperatorEquals_OneNull_ShouldReturnFalse()
    {
        var product = FakeData.CreateProduct();
        Product? nullProduct = null;

        (product == nullProduct).Should().BeFalse();
        (nullProduct == product).Should().BeFalse();
    }

    [Fact]
    public void OperatorNotEquals_DifferentEntities_ShouldReturnTrue()
    {
        var a = FakeData.CreateProduct();
        var b = FakeData.CreateProduct();

        (a != b).Should().BeTrue();
    }

    [Fact]
    public void GetHashCode_ShouldBeBasedOnId()
    {
        var product = FakeData.CreateProduct();
        product.GetHashCode().Should().Be(product.Id.GetHashCode());
    }

    [Fact]
    public void ClearDomainEvents_ShouldRemoveAllEvents()
    {
        var product = FakeData.CreateProduct(stock: 10, minimumStock: 5);
        product.AdjustStock(-6, StockMovementType.StockOut);
        product.DomainEvents.Should().NotBeEmpty();

        product.ClearDomainEvents();

        product.DomainEvents.Should().BeEmpty();
    }

    [Fact]
    public void SoftDelete_DefaultValues_ShouldNotBeDeleted()
    {
        var product = FakeData.CreateProduct();

        product.IsDeleted.Should().BeFalse();
        product.DeletedAt.Should().BeNull();
        product.DeletedBy.Should().BeNull();
    }

    [Fact]
    public void AuditFields_ShouldHaveDefaultValues()
    {
        var product = FakeData.CreateProduct();

        product.CreatedBy.Should().Be("system");
        product.UpdatedBy.Should().Be("system");
        product.CreatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(5));
    }

    [Fact]
    public void Id_ShouldBeAutoGenerated()
    {
        var a = FakeData.CreateProduct();
        var b = FakeData.CreateProduct();

        a.Id.Should().NotBe(Guid.Empty);
        b.Id.Should().NotBe(Guid.Empty);
        a.Id.Should().NotBe(b.Id);
    }
}
